"""Tiploc table

Revision ID: 5ec6e9da08f8
Revises: 
Create Date: 2022-04-09 08:13:53.294546

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5ec6e9da08f8'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tiploc',
    sa.Column('tiploc_code', sa.String(10), nullable=False),
    sa.Column('nalco', sa.String(10), nullable=True),
    sa.Column('stanox', sa.String(10), nullable=True),
    sa.Column('crs_code', sa.String(10), nullable=True),
    sa.Column('description', sa.String(255), nullable=True),
    sa.Column('tps_description', sa.String(255), nullable=True),
    sa.PrimaryKeyConstraint('tiploc_code')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('tiploc')
    # ### end Alembic commands ###
