"""Add tiploc

Revision ID: 4bc291ead928
Revises: f3c7e58d810b
Create Date: 2022-04-09 14:21:14.305079

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4bc291ead928'
down_revision = 'f3c7e58d810b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
