"""Add tiploc

Revision ID: f3c7e58d810b
Revises: 
Create Date: 2022-04-09 14:20:44.448528

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f3c7e58d810b'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tiploc',
    sa.Column('internal_tiploc_id', sa.Integer(), nullable=False, auto_increment=True),
    sa.Column('tiploc_code', sa.String(length=10), nullable=True),
    sa.Column('nalco', sa.String(length=10), nullable=True),
    sa.Column('stanox', sa.String(length=10), nullable=True),
    sa.Column('crs_code', sa.String(length=10), nullable=True),
    sa.Column('description', sa.String(length=100), nullable=True),
    sa.Column('tps_description', sa.String(length=100), nullable=True),
    sa.PrimaryKeyConstraint('internal_tiploc_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('tiploc')
    # ### end Alembic commands ###
